- update readme instructions from test walk thru on clean mac
- was seeing error message during grunt test

```
Running "mochaTest:test" (mochaTest) task
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

- to fix run npm install bunyan to correct missing module and included node_module bunyan files